const ACCESS_TOKEN_SECRET="timepassplay"
const ACCESS_TOKEN_EXPIRY="1d"
const REFRESH_TOKEN_SECRET="timepassplay071292nikhilmore"
const REFRESH_TOKEN_EXPIRY="10d"

export {ACCESS_TOKEN_EXPIRY,ACCESS_TOKEN_SECRET,REFRESH_TOKEN_EXPIRY,REFRESH_TOKEN_SECRET}